import {
  businessLineMap,
  genderMap,
  levelMap,
  PAGES,
  percentageBins,
  POSITIONS_OPTIONS,
  QUESTION_TYPE,
} from '@constants'
import { getRoleSpecificPage } from '@functions'
import { SurveySection } from '@types'

function fieldMin(val: number) {
  return { min: { value: val, message: `The value must be at least ${val}` } }
}

function fieldMax(val: number) {
  return { max: { value: val, message: `The value must be at most ${val}` } }
}
export const survey: SurveySection[] = [
  {
    internalName: 'General',
    title: 'General',
    next: getRoleSpecificPage,
    back: false,
    questions: [
      {
        name: 'gender',
        type: QUESTION_TYPE.MCQ,
        label: "You're a",
        choices: Object.values(genderMap),
        isRequired: true,
      },
      {
        name: 'age',
        type: QUESTION_TYPE.NUMBER,
        label: 'How old are you?',
        isRequired: true,
        validationRules: { ...fieldMin(16), ...fieldMax(100) },
      },
      {
        name: 'degree',
        type: QUESTION_TYPE.MCQ,
        label: 'Do you have a computer science/engineering degree?',
        choices: ['Yes', 'No'],
        isRequired: true,
      },
      {
        name: 'linkedin',
        type: QUESTION_TYPE.STRING,
        label: 'Your Linkedin Profile',
        isRequired: false,
      },
      {
        name: 'email',
        type: QUESTION_TYPE.STRING,
        label: 'Your email address',
        isRequired: false,
      },
      {
        name: 'company',
        type: QUESTION_TYPE.STRING,
        label: 'Your current company:',
        isRequired: true,
      },
      {
        name: 'job-title',
        type: QUESTION_TYPE.STRING,
        label: 'Your job title:',
        isRequired: true,
      },
      {
        name: 'role',
        type: QUESTION_TYPE.MCQ,
        label: 'Do you consider yourself a/an',
        choices: POSITIONS_OPTIONS.map((pos) => pos.positionName),
        isRequired: true,
      },
      {
        name: 'level',
        type: QUESTION_TYPE.MCQ,
        label: 'Your level at your current company is:',
        choices: Object.values(levelMap),
        isRequired: true,
      },
      {
        name: 'years-experience',
        type: QUESTION_TYPE.NUMBER,
        label: 'Years of experience:',
        isRequired: true,
      },
      {
        name: 'companies-last-5',
        type: QUESTION_TYPE.NUMBER,
        label: 'How many companies did you work at in the last 5 years?',
        isRequired: true,
        validationRules: { ...fieldMax(10) },
      },
      {
        name: 'same-company',
        type: QUESTION_TYPE.MCQ,
        label: 'Did you work at the same company last year (January 2023) ?',
        choices: ['Yes', 'No'],
        isRequired: false,
      },
      {
        name: 'employee-location',
        type: QUESTION_TYPE.MCQ,
        label: 'You work from',
        choices: [
          'Office for a company in Egypt',
          'Home for a company in Egypt',
          'Hybrid for a company in Egypt (e.g 2-3 days from home or office)',
          'Home for a company abroad (Remote employee)',
          'Abroad in another country (Relocated elsewhere)',
        ],
        isRequired: true,
      },
      {
        name: 'company-size',
        type: QUESTION_TYPE.MCQ,
        label: 'Your company is considered:',
        choices: [
          'A Start-up',
          'A Small and Medium Enterprise',
          'A Large Enterprise/Multinational Company',
        ],
        isRequired: true,
      },
      {
        name: 'company-location',
        type: QUESTION_TYPE.MCQ,
        label: "Company Location in case it's operating from Egypt:",
        choices: [
          'No site in Egypt',
          'Cairo',
          'Alexandria',
          'Hurghada (Or Gouna)',
          'Port Said / Suez',
          'Mansoura',
          'Faiyum',
          'Luxor / Aswan',
          'Other',
        ],
        isRequired: true,
      },
      {
        name: 'company-type',
        type: QUESTION_TYPE.MCQ,
        label: 'You work in a:',
        choices: ['Software House', 'Product-based company', 'Other'],
        isRequired: true,
      },
      {
        name: 'business-focus',
        type: QUESTION_TYPE.MCQ,
        label: 'The business main focus is:',
        choices: Object.values(businessLineMap),
        isRequired: true,
      },
      {
        name: 'business-scope',
        type: QUESTION_TYPE.MCQ,
        label: 'The business is',
        choices: [
          'Local / National (operates inside Egypt)',
          'Regional (has some business lines in Saudi Arabia, Emirates, etc)',
          'Global (has some business lines in the region, the US, Europe, Asia, etc.)',
        ],
        isRequired: false,
      },
      {
        name: 'business-industries',
        type: QUESTION_TYPE.CHECKBOX,
        label: 'The industries of the business are',
        choices: [
          'Fintech',
          'Healthcare',
          'Insurance',
          'Automotive',
          'Delivery',
          'Supply Chain',
          'Transportation',
          'Telecommunications',
          'Energy',
          'Manufacturing',
          'Technology',
          'Education',
          'Human Resources Services',
          'Law',
          'Agriculture',
          'Production',
          'Aerospace',
          'Other',
        ],
        isRequired: false,
      },
    ],
  },
  {
    internalName: 'Engineering-Skills',
    title: 'Skills',
    next: PAGES.ENGINEERING_ACTIVITIES, // You might want to add a function here if needed
    back: true,
    questions: [
      {
        name: 'programming-languages',
        type: QUESTION_TYPE.CHECKBOX,
        label: 'Which programming languages do you use the most?',
        choices: [
          'C#',
          'Java',
          'PHP',
          'JavaScript',
          'Python',
          'Go',
          'Rust',
          'Ruby',
          'C/C++',
          'TypeScript',
          'Scala',
          'Kotlin',
          'Swift',
          'R',
          'HTML/CSS',
          'Other:',
        ],
        isRequired: false,
      },
      {
        name: 'frameworks',
        type: QUESTION_TYPE.CHECKBOX,
        label: 'Which frameworks do you use the most?',
        choices: [
          'ASP.Net',
          'Spring',
          'Django',
          'Flask',
          'Laravel',
          'Express',
          'FastAPI',
          'Ruby on Rails',
          'React',
          'Angular',
          'JQuery',
          'Vue.js',
          'NestJS',
          'Nuxt.js',
          'Next.js',
          'Gatsby',
          'Deno',
          'Tensorflow',
          'Pytorch',
          'OpenCV',
          'Autosar',
          'React Native',
          'Ionic',
          'Flutter',
          'Android',
          'Other:',
        ],
        isRequired: false,
      },
      {
        name: 'cloud-providers',
        type: QUESTION_TYPE.CHECKBOX,
        label: 'Which cloud provider hosts the services you help in building?',
        choices: ['AWS', 'GCP', 'Azure', 'Cloudflare', 'Firebase', 'Self-hosted', 'Other:'],
        isRequired: false,
      },
      {
        name: 'databases',
        type: QUESTION_TYPE.CHECKBOX,
        label: 'Which databases do you use the most?',
        choices: [
          'PostgreSQL',
          'MySQL',
          'SQLite',
          'MongoDB',
          'SQL Server',
          'Redis',
          'MariaDB',
          'ElasticSearch',
          'Oracle',
          'DynamoDB',
          'Cassandra',
          'Firebase',
          'Other:',
        ],
        isRequired: false,
      },
      {
        name: 'technologies',
        type: QUESTION_TYPE.CHECKBOX,
        label: 'Which of these technologies do you use in your daily activities?',
        choices: [
          'Kubernetes',
          'Docker',
          'Terraform',
          'Jenkins',
          'TeamCity',
          'CircleCI',
          'TravisCI',
          'Kafka',
          'RabbitMQ',
          'Spark',
          'Redshift',
          'Snowflake',
          'BigQuery',
          'Airflow',
          'Tableu',
          'Looker',
          'Hive',
          'PowerBI',
          'Other:',
        ],
        isRequired: false,
      },
    ],
  },
  {
    internalName: 'Engineering-Activities',
    title: 'Activities',
    next: PAGES.SALARY,
    back: true,
    questions: [
      {
        name: 'coding-percentage',
        type: QUESTION_TYPE.MCQ,
        label: 'What percentage of your week is spent in coding/testing/implementing?',
        choices: percentageBins,
        isRequired: false,
      },
      {
        name: 'designing-percentage',
        type: QUESTION_TYPE.MCQ,
        label: 'What percentage of your week is spent in designing?',
        choices: percentageBins,
        isRequired: false,
      },
      {
        name: 'engineering-meetings-percentage',
        type: QUESTION_TYPE.MCQ,
        label: 'What percentage of your week is spent in meetings?',
        choices: percentageBins,
        isRequired: false,
      },
      {
        name: 'mentoring-percentage',
        type: QUESTION_TYPE.MCQ,
        label: 'What percentage of your week is spent in mentoring?',
        choices: percentageBins,
        isRequired: false,
      },
    ],
  },
  {
    internalName: 'Management-Activities',
    title: 'Activities',
    next: PAGES.SALARY,
    back: true,
    questions: [
      {
        name: 'onboarding-duration',
        type: QUESTION_TYPE.MCQ,
        label: 'How long does it take to onboard a new talent in your team?',
        choices: ['2 Weeks', '1 Month', '2 Months', 'Other:'],
        isRequired: true,
      },
      {
        name: 'senior-hiring-duration',
        type: QUESTION_TYPE.MCQ,
        label: 'How long does it usually take to hire a senior talent?',
        choices: ['1 Month', '1-3 Months', '3-5 Months', '5+ Months', 'Other:'],
        isRequired: true,
      },
      {
        name: 'management-planning-percentage',
        type: QUESTION_TYPE.MCQ,
        label: 'What percentage of your week is spent in planning?',
        choices: percentageBins,
        isRequired: true,
      },
      {
        name: 'management-meetings-percentage',
        type: QUESTION_TYPE.MCQ,
        label: 'What percentage of your week is spent in meetings?',
        choices: percentageBins,
        isRequired: true,
      },
      {
        name: 'mentoring-percentage',
        type: QUESTION_TYPE.MCQ,
        label: 'What percentage of your week is spent in mentoring?',
        choices: percentageBins,
        isRequired: true,
      },
    ],
  },
  {
    // Product Activities
    internalName: 'Product-Activities',
    title: 'Activities',
    next: PAGES.SALARY,
    back: true,
    questions: [
      {
        name: 'quarterly-activities',
        type: QUESTION_TYPE.CHECKBOX,
        label: 'Which functions of these are part of your quarterly activities?',
        choices: [
          'Collaborating with technical and design functions',
          'Collaborating with other functions',
          'Defining product strategy',
          'Define product requirements',
          'Engaging with customers and partners',
          'Reviewing metrics',
          'Market research and competition',
          'Planning and maintaining roadmaps',
          'Pricing and packaging',
          'Coaching, team management and recruiting',
        ],
        isRequired: false,
      },
      {
        name: 'product-planning-percentage',
        type: QUESTION_TYPE.MCQ,
        label: 'What percentage of your week is spent in planning?',
        choices: percentageBins,
        isRequired: false,
      },
      {
        name: 'product-meetings-percentage',
        type: QUESTION_TYPE.MCQ,
        label: 'What percentage of your week is spent in meetings?',
        choices: percentageBins,
        isRequired: false,
      },
      {
        name: 'data-analysis-percentage',
        type: QUESTION_TYPE.MCQ,
        label: 'What percentage of your week is spent analyzing data?',
        choices: percentageBins,
        isRequired: false,
      },
      {
        name: 'weekly-tools',
        type: QUESTION_TYPE.CHECKBOX,
        label: 'Which of these tools do you use in your weekly activities?',
        choices: [
          'Notion',
          'Obsidian',
          'Jira',
          'Trello',
          'Miro',
          'Hotjar',
          'Confluence',
          'Looker Studio',
          'Power BI',
          'Amplitude',
          'UX Pin',
          'ProductBoard',
          'ProductPlan',
          'Aha!',
          'Tableau',
          'SurveyMonkey',
          'Typeform',
          'UserVoice',
          'Gartner',
          'Figma',
          'Adobe XD',
          'Proto.io',
          'ClickUp',
        ],
        isRequired: false,
      },
      {
        name: 'survey-tools',
        type: QUESTION_TYPE.STRING,
        label: 'Which tools do you use for customer surveys?',
        isRequired: false,
      },
      {
        name: 'project-management-tools',
        type: QUESTION_TYPE.STRING,
        label: 'Which tools do you use for project management?',
        isRequired: false,
      },
      {
        name: 'pricing-decision-maker',
        type: QUESTION_TYPE.MCQ,
        label: 'Who takes pricing and packaging decisions for your product?',
        choices: [
          'You',
          'Executive team (C-Level)',
          'Sales & Marketing',
          'We have dedicated pricing team (or RevOps)',
          'Other:',
        ],
        isRequired: false,
      },
      {
        name: 'ai-assistant-use',
        type: QUESTION_TYPE.STRING,
        label:
          'When do you find it super useful to use the help of an AI assistant (ChatGPT, Gemini, etc.)',
        isRequired: false,
      },
      {
        name: 'prototype-tools',
        type: QUESTION_TYPE.STRING,
        label: 'If you had a product idea, which tools would you use to build a prototype?',
        isRequired: false,
      },
      {
        name: 'ab-testing-tools',
        type: QUESTION_TYPE.STRING,
        label: 'Which tools do you use for A/B Testing (or feature flagging)?',
        isRequired: false,
      },
      {
        name: 'data-analysis-tools',
        type: QUESTION_TYPE.MCQ,
        label: 'What are your go-to tools to analyze data?',
        choices: [
          'Sheets/Excel',
          'SQL (or database query languages in general)',
          'Programming Languages (e.g python, R, etc.)',
          'Other:',
        ],
        isRequired: false,
      },
      {
        name: 'no-code-prototype-tools',
        type: QUESTION_TYPE.STRING,
        label: 'Which no-code tool do you find very powerful to build a prototype with?',
        isRequired: false,
      },
      {
        name: 'session-replay-tools',
        type: QUESTION_TYPE.STRING,
        label: 'Which session replay and heatmap tools do you use?',
        isRequired: false,
      },
      {
        name: 'user-analysis-tools',
        type: QUESTION_TYPE.STRING,
        label: 'Which user analysis tools do you use?',
        isRequired: false,
      },
    ],
  },
  {
    internalName: 'Salary',
    title: 'Salary',
    next: PAGES.SATISFACTION,
    back: true,
    questions: [
      {
        name: 'salary-currency',
        type: QUESTION_TYPE.MCQ,
        label: 'In what currency do you receive your salary?',
        choices: [
          'EGP',
          'Another currency (e.g USD)',
          'Hybrid (e.g: Base in EGP and Cost of Living Allowance in EUR)',
        ],
        isRequired: true,
      },
      {
        name: 'pegged-to-central-bank',
        type: QUESTION_TYPE.MCQ,
        label:
          "If part or all your salary is pegged to another currency, is it pegged to the central bank's transfer rate?",
        choices: ['Yes', 'No'],
        isRequired: false,
      },
      {
        name: 'other-currency',
        type: QUESTION_TYPE.MCQ,
        label:
          "If you receive your salary in (or if it's pegged to) another currency or in a hybrid setting, what's the other currency (Let's call it X)?",
        choices: ['USD', 'EUR', 'SAR', 'AED', 'GBP', 'KWD', 'Other:'],
        isRequired: false,
      },
      {
        name: 'egp-net-monthly-salary',
        type: QUESTION_TYPE.NUMBER,
        label: 'EGP Net Monthly Salary',
        isRequired: true,
      },
      {
        name: 'x-net-monthly-salary',
        type: QUESTION_TYPE.NUMBER,
        label: 'X Net Monthly Salary',
        isRequired: true,
      },
      {
        name: 'egp-net-monthly-bonus',
        type: QUESTION_TYPE.NUMBER,
        label: 'EGP Net Monthly Bonus',
        isRequired: true,
      },
      {
        name: 'x-net-monthly-bonus',
        type: QUESTION_TYPE.NUMBER,
        label: 'X Net Monthly Bonus',
        isRequired: true,
      },
      {
        name: 'stocks-value-one-year',
        type: QUESTION_TYPE.NUMBER,
        label:
          "If you're receiving stocks/equity, what's the value in ONE YEAR (In USD, 2 thousands == 2000)",
        isRequired: false,
      },
      {
        name: 'extra-notes',
        type: QUESTION_TYPE.STRING,
        label:
          "Do you want to add any notes about your bonuses that weren't covered in the previous questions?",
        isRequired: false,
      },
      {
        name: 'last-salary-increase',
        type: QUESTION_TYPE.MCQ,
        label: 'When was your most recent salary increase implemented?',
        choices: [
          'A new hire',
          'Less than 3 months',
          'Less than 6 months',
          'Less than a year',
          'More than a year',
        ],
        isRequired: false,
      },
      {
        name: 'net-salary-dec2022',
        type: QUESTION_TYPE.NUMBER,
        label:
          'What was your EGP NET salary in December 2022 including any bonuses (USD == 24.5 EGP then)',
        isRequired: false,
      },
      {
        name: 'expected-new-job-salary',
        type: QUESTION_TYPE.NUMBER,
        label:
          'If you were to apply for a new job, how much will your expected net salary be in EGP?',
        isRequired: false,
      },
    ],
  },
  {
    internalName: 'Satisfaction',
    title: 'Satisfaction',
    back: true,
    questions: [
      {
        name: 'earn-deserved',
        type: QUESTION_TYPE.MCQ,
        label: 'Do you think you earn what you deserve?',
        choices: [
          'Yes',
          'No, I should earn more than that',
          'No, I should earn less than that',
          'Not sure',
        ],
        isRequired: false,
      },
      {
        name: 'level-deserved',
        type: QUESTION_TYPE.MCQ,
        label: 'Do you think you are placed in the level you deserve?',
        choices: [
          'Yes',
          'No, I should be in a higher level',
          'No, I should be in a lesser level',
          'Not sure',
        ],
        isRequired: false,
      },
      {
        name: 'work-value',
        type: QUESTION_TYPE.MCQ,
        label: 'Do you find value in your work?',
        choices: ['Yes', 'No', "I don't care, just here for the $"],
        isRequired: false,
      },
      {
        name: 'learning-opportunities',
        type: QUESTION_TYPE.MCQ,
        label: 'Are you presented with the chance to learn new things in your job?',
        choices: ['Yes', 'No', 'Sometimes'],
        isRequired: false,
      },
      {
        name: 'preferred-environment',
        type: QUESTION_TYPE.MCQ,
        label: 'Which work environment do you prefer?',
        choices: ['Remote', 'In-person', 'Hybrid (some remote, some in-person)'],
        isRequired: false,
      },
    ],
  },
]
